# Generated by Django 3.1.1 on 2020-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Calendar Master',
            },
        ),
        migrations.CreateModel(
            name='calendar_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Calendar User',
            },
        ),
        migrations.CreateModel(
            name='financialYear_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=100, unique=True)),
                ('assessment_year', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Financial Year Master',
            },
        ),
        migrations.CreateModel(
            name='form_return_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_return', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Form/Return Master',
            },
        ),
        migrations.CreateModel(
            name='frequency_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Frequency Master',
            },
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=100)),
                ('financial_year', models.CharField(max_length=100)),
                ('assessment_year', models.CharField(max_length=100)),
                ('date_of_entry', models.DateField(auto_now=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('form_return', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('type_of_tax_payer', models.CharField(max_length=100)),
                ('actual_due_date', models.DateField()),
                ('Description', models.CharField(max_length=100)),
                ('due_date_1', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_1_remarks', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_2', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_2_remarks', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_3', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_3_remarks', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_4', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_4_remarks', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_5', models.CharField(default='null', max_length=100, null=True)),
                ('due_date_5_remarks', models.CharField(default='null', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Task Master',
            },
        ),
        migrations.CreateModel(
            name='regulator_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator', models.CharField(max_length=100, unique=True)),
                ('color_palette', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Regulator Master',
            },
        ),
        migrations.CreateModel(
            name='tax_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_payer', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Tax Master',
            },
        ),
    ]
