# Generated by Django 3.1.1 on 2020-10-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='assessment_year',
            field=models.ForeignKey(db_column='assessment_year', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='LoginSystem.financialyear_master', to_field='assessment_year'),
        ),
    ]
