# Generated by Django 3.1.1 on 2020-10-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0002_auto_20201023_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='assessment_year',
            new_name='assessment_year1',
        ),
    ]
