# Generated by Django 3.1.1 on 2020-10-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0003_auto_20201023_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='assessment_year1',
            new_name='assessment_year',
        ),
    ]
