# Generated by Django 3.1.1 on 2020-10-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0004_auto_20201023_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='assessment_year',
            new_name='assessment_year_rd',
        ),
    ]
