# Generated by Django 3.1.1 on 2020-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0005_auto_20201023_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='assessment_year_rd',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='assessment_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
