# Generated by Django 3.1.1 on 2020-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0006_auto_20201023_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='assessment_year',
            new_name='financial_assessment_year',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='financial_year',
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='date_of_entry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
