# Generated by Django 3.1.1 on 2020-10-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0007_auto_20201023_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='date_of_entry',
            field=models.DateField(auto_now=True),
        ),
    ]
