# Generated by Django 3.1.1 on 2020-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0008_auto_20201023_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='financialYear_master',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='financial_assessment_year',
            new_name='assessment_year',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='financial_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
