# Generated by Django 3.1.1 on 2020-11-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0011_auto_20201108_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Signup Data',
            },
        ),
        migrations.RenameField(
            model_name='calendar_user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='calendar_user',
            name='password2',
        ),
    ]
