# Generated by Django 3.1.1 on 2020-11-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0012_auto_20201108_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='email_id',
        ),
    ]
