# Generated by Django 3.1.1 on 2020-11-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0013_remove_signupdata_email_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calendar_user',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='qualification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
