# Generated by Django 3.1.1 on 2020-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0014_auto_20201108_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdata',
            name='password',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='qualification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
