# Generated by Django 3.1.1 on 2020-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0015_auto_20201108_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='latest_due_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
